name: Deploy Backend to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.AWS_EC2_USER }}/compete-nest
            git pull origin main

            cd backend
            npm install
            npm run build

            # Restart the main backend server
            sudo pm2 stop competenest || true
            sudo pm2 delete competenest || true
            sudo pm2 start src/server.ts --name competenest --interpreter ts-node

            # Restart the contest worker
            sudo pm2 stop contest-worker || true
            sudo pm2 delete contest-worker || true
            sudo pm2 start ts-node --name contest-worker -- src/bullmq/workers/contestWorkers.ts

            # Save PM2 process list
            sudo pm2 save
