name: Deploy Backend to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.AWS_EC2_USER }}/compete-nest
            git pull origin main

            cd backend/src
            npm install
            npm run build

            #Restart the main backend server
            sudo pm2 restart competenest || true

            # Save PM2 process list
            sudo pm2 save
